runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:mjF4D221LJMO4JOKyntwqP8V7ioreKyDaaSz8+8E/0M=
  STORAGE_DIR: /tmp
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: yalla_mana
  DB_PORT: 3306
  DB_USERNAME: root
  DB_PASSWORD: majdbb18
  DB_SOCKET: "/cloudsql/yalla-mana:us-central1:yallamana"

beta_settings:
  cloud_sql_instances: "yalla-mana:us-central1:yallamana"
      # for Cloud SQL, set this value to the Cloud SQL connection name,
      # e.g. "project:region:cloudsql-instance"



